/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.ManageStudentsWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.StudentProfile;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;

/**
 *
 * @author RIO
 */
public class ManageStudentsJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;

    /**
     * Creates new form ManageStudentsJPanel
     */
    public ManageStudentsJPanel(Business bz, JPanel jp) {
        this.business = bz;
        this.CardSequencePanel = jp;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        IDField = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        btnAddStudent = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        lblEmail = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        lblDepartments = new javax.swing.JLabel();
        DepartmentField = new javax.swing.JTextField();
        lblContacts = new javax.swing.JLabel();
        ContactField = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnDelete1 = new javax.swing.JButton();
        CBStatus = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Manage Students");
        add(jLabel1);
        jLabel1.setBounds(200, 20, 190, 40);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(20, 430, 74, 23);
        add(IDField);
        IDField.setBounds(90, 80, 150, 30);

        lblID.setText("Student ID:");
        add(lblID);
        lblID.setBounds(20, 80, 70, 30);

        lblName.setText("Name:");
        add(lblName);
        lblName.setBounds(20, 120, 37, 30);
        add(NameField);
        NameField.setBounds(90, 120, 150, 30);

        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        add(btnAddStudent);
        btnAddStudent.setBounds(20, 360, 120, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(180, 360, 72, 23);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Department", "Contact", "Status"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        add(jScrollPane1);
        jScrollPane1.setBounds(250, 80, 420, 130);

        lblEmail.setText("Email:");
        add(lblEmail);
        lblEmail.setBounds(20, 160, 37, 30);
        add(EmailField);
        EmailField.setBounds(90, 160, 150, 30);

        lblDepartments.setText("Department:");
        add(lblDepartments);
        lblDepartments.setBounds(20, 200, 90, 30);
        add(DepartmentField);
        DepartmentField.setBounds(90, 200, 150, 30);

        lblContacts.setText("Contact:");
        add(lblContacts);
        lblContacts.setBounds(20, 240, 70, 30);
        add(ContactField);
        ContactField.setBounds(90, 240, 150, 30);

        lblStatus.setText("Status:");
        add(lblStatus);
        lblStatus.setBounds(20, 280, 37, 30);

        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        add(btnDelete1);
        btnDelete1.setBounds(290, 360, 72, 23);

        CBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "On Leave", "Graduated", " " }));
        CBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBStatusActionPerformed(evt);
            }
        });
        add(CBStatus);
        CBStatus.setBounds(90, 280, 150, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // TODO add your handling code here:
        //RijurikSaha-RegisterPerson-10/24
        String id = IDField.getText().trim();
        String name = NameField.getText().trim();
        String email = EmailField.getText().trim();
        String dept = DepartmentField.getText().trim();
        String contact = ContactField.getText().trim();
        String status = CBStatus.getSelectedItem().toString();

        // Validation
        if (id.isEmpty() || name.isEmpty() || email.isEmpty() || dept.isEmpty() || contact.isEmpty()) {
            JOptionPane.showMessageDialog(this, "️ Please fill all fields before adding a student!");
            return;
        }

        // Check if student already exists
        Person existing = business.getPersonDirectory().findPerson(id);
        if (existing != null) {
            JOptionPane.showMessageDialog(this, " A student with this ID already exists!");
            return;
        }

        // Create and register new Person
        Person newStudent = business.getPersonDirectory()
                .newPerson(id, name, email, dept, "Student", contact, status);

        // Also register in StudentDirectory (optional — to maintain both lists)
        business.getStudentDirectory().newStudentProfile(newStudent);

        JOptionPane.showMessageDialog(this, "Student added successfully!");

        clearFields();
        populateTable();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //RijurikSaha-RegisterPerson-10/24
        int selectedRow = tblStudents.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "️ Please select a student from the table to update!");
            return;
        }

        String id = tblStudents.getValueAt(selectedRow, 0).toString();
        Person existing = business.getPersonDirectory().findPerson(id);

        if (existing != null) {
            existing.setName(NameField.getText().trim());
            existing.setEmail(EmailField.getText().trim());
            existing.setDepartment(DepartmentField.getText().trim());
            existing.setContact(ContactField.getText().trim());
            existing.setAcademicStatus(CBStatus.getSelectedItem().toString());

            JOptionPane.showMessageDialog(this, " Student record updated successfully!");
            populateTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, " Student not found!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStudents.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student to delete!");
            return;
        }

        String id = tblStudents.getValueAt(selectedRow, 0).toString();

        // Remove from PersonDirectory only
        Person p = business.getPersonDirectory().findPerson(id);
        if (p != null) {
            business.getPersonDirectory().removePerson(p);
        }

        JOptionPane.showMessageDialog(this, "Student deleted successfully!");
        populateTable();
        clearFields();
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void CBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBStatusActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblStudents.getSelectedRow();
        if (selectedRow >= 0) {
            IDField.setText(tblStudents.getValueAt(selectedRow, 0).toString());
            NameField.setText(tblStudents.getValueAt(selectedRow, 1).toString());
            EmailField.setText(tblStudents.getValueAt(selectedRow, 2).toString());
            DepartmentField.setText(tblStudents.getValueAt(selectedRow, 3).toString());
            ContactField.setText(tblStudents.getValueAt(selectedRow, 4).toString());
            CBStatus.setSelectedItem(tblStudents.getValueAt(selectedRow, 5).toString());
        }
    }//GEN-LAST:event_tblStudentsMouseClicked
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);

        // Load all students from PersonDirectory
        for (Person p : business.getPersonDirectory().getPersonList()) {
            if ("Student".equalsIgnoreCase(p.getRole())) {
                model.addRow(new Object[]{
                    p.getPersonId(),
                    p.getName(),
                    p.getEmail(),
                    p.getDepartment(),
                    p.getContact(),
                    p.getAcademicStatus()
                });
            }
        }
    }

    private void clearFields() {
        IDField.setText("");
        NameField.setText("");
        EmailField.setText("");
        DepartmentField.setText("");
        ContactField.setText("");
        CBStatus.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> CBStatus;
    private javax.swing.JTextField ContactField;
    private javax.swing.JTextField DepartmentField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContacts;
    private javax.swing.JLabel lblDepartments;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables
}
