/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.MyProfileWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author RIO
 */
public class MyProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyProfileJPanel
     */
    Business business;
    JPanel CardSequencePanel;
    UserAccount userAccount;

    public MyProfileJPanel(Business b, JPanel cards, UserAccount ua) {
        this.business = b;
        this.CardSequencePanel = cards;
        this.userAccount = ua;
        initComponents();
        loadAdminProfile(); // load data when screen opens
    }

    private void loadAdminProfile() {
        if (userAccount == null) {
            JOptionPane.showMessageDialog(this, "No admin user loaded!");
            return;
        }

        // Get the associated person object
        Person p = userAccount.getAssociatedPersonProfile().getPerson();

        // Populate fields
        IDField.setText(p.getPersonId());
        NameField.setText(p.getName());
        EmailField.setText(p.getEmail());
        DepartmentField.setText(p.getDepartment());
        ContactField.setText(p.getContact());
        CBStatus.setSelectedItem(p.getAcademicStatus());

        // Make ID non-editable
        IDField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        lblDepartments = new javax.swing.JLabel();
        DepartmentField = new javax.swing.JTextField();
        lblContacts = new javax.swing.JLabel();
        ContactField = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        CBStatus = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Admin Profile");
        add(jLabel1);
        jLabel1.setBounds(260, 10, 190, 40);
        add(IDField);
        IDField.setBounds(280, 70, 150, 30);

        lblID.setText("Admin ID:");
        add(lblID);
        lblID.setBounds(210, 70, 70, 30);

        lblName.setText("Name:");
        add(lblName);
        lblName.setBounds(210, 110, 37, 30);
        add(NameField);
        NameField.setBounds(280, 110, 150, 30);

        lblEmail.setText("Email:");
        add(lblEmail);
        lblEmail.setBounds(210, 150, 37, 30);
        add(EmailField);
        EmailField.setBounds(280, 150, 150, 30);

        lblDepartments.setText("Department:");
        add(lblDepartments);
        lblDepartments.setBounds(210, 190, 90, 30);
        add(DepartmentField);
        DepartmentField.setBounds(280, 190, 150, 30);

        lblContacts.setText("Contact:");
        add(lblContacts);
        lblContacts.setBounds(210, 230, 70, 30);
        add(ContactField);
        ContactField.setBounds(280, 230, 150, 30);

        lblStatus.setText("Status:");
        add(lblStatus);
        lblStatus.setBounds(210, 270, 37, 30);

        CBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "On Leave", "Graduated", " " }));
        CBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBStatusActionPerformed(evt);
            }
        });
        add(CBStatus);
        CBStatus.setBounds(280, 270, 150, 30);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(320, 320, 75, 23);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(320, 350, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void CBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBStatusActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (userAccount == null) {
            JOptionPane.showMessageDialog(this, "No admin user found!");
            return;
        }

        Person p = userAccount.getAssociatedPersonProfile().getPerson();

        // Update fields
        p.setName(NameField.getText().trim());
        p.setEmail(EmailField.getText().trim());
        p.setDepartment(DepartmentField.getText().trim());
        p.setContact(ContactField.getText().trim());
        p.setAcademicStatus(CBStatus.getSelectedItem().toString());

        JOptionPane.showMessageDialog(this, "Profile updated successfully!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBStatus;
    private javax.swing.JTextField ContactField;
    private javax.swing.JTextField DepartmentField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContacts;
    private javax.swing.JLabel lblDepartments;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
